version: "3.8"

services:
    webapp-app:
        container_name: "webapp-app"
        image: "webapp-app:1.0.0"
        build:
            context: "."
            dockerfile: "dev/Dockerfile"
        ports:
            - "7860:7860"
        volumes:
            - "./app:/app"
